[[databases]]
uuid = "primary"
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
dbname = "primary_db"

[[databases]]
uuid = "secondary"
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
dbname = "secondary_db"