[[databases]]
uuid = "7b961b3b-4cf5-40fc-9c8e-d7237def1a3a"
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
dbname = "primary_db"

[[databases]]
uuid = "830e70ce-d25d-4f16-a6e6-5e5e88d4d30e"
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
dbname = "secondary_db"